# Generated by Django 6.0.6 on 2026-10-07 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text="The account's username when the event was recorded.", max_length=150)),
                ('kind', models.CharField(choices=[('sign_up', 'Signed up'), ('sign_in_succeeded', 'Signed in'), ('sign_in_failed', 'Sign-in failed'), ('2fa_code_failed', 'Two-factor code failed'), ('password_changed', 'Password changed'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('email_change_requested', 'Email change requested'), ('email_change_confirmed', 'Email changed'), ('email_verified', 'Email verified'), ('username_changed', 'Username changed'), ('2fa_enabled', 'Two-factor turned on'), ('2fa_disabled', 'Two-factor turned off'), ('2fa_reset', 'Two-factor reset'), ('recovery_codes_regenerated', 'Recovery codes regenerated'), ('recovery_code_used', 'Recovery code used'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('cooldown_cleared', 'Sign-in cooldown cleared'), ('other_sessions_ended', 'Signed out of other devices')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='securityevent_user_recent')],
            },
        ),
    ]
