# Generated by Django 6.0.6 on 2026-10-07 21:15

import accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def refuse_case_insensitive_duplicates(apps, schema_editor):
    """Stop before the constraints if existing accounts already clash.

    Adding the constraints over duplicates would fail anyway, but with a
    bare IntegrityError that names nobody. This names every clash so a
    person can resolve it — the migration never merges or renames
    accounts itself. Values are folded with the database's own ``LOWER``,
    the same expression the constraints use, so this check and the
    constraints can't disagree about what counts as a duplicate.
    """
    User = apps.get_model("accounts", "User")
    clashes = []
    for field in ("username", "email"):
        rows = User.objects.exclude(**{field: ""}).annotate(folded=Lower(field))
        duplicated = (
            rows.values("folded")
            .annotate(count=Count("pk"))
            .filter(count__gt=1)
            .order_by("folded")
            .values_list("folded", flat=True)
        )
        for folded in duplicated:
            values = rows.filter(folded=folded).order_by("pk")
            listed = ", ".join(
                repr(value) for value in values.values_list(field, flat=True)
            )
            clashes.append(f"  {field}: {listed}")
    if clashes:
        raise RuntimeError(
            "Can't make usernames and emails unique case-insensitively: "
            "these accounts clash.\n"
            + "\n".join(clashes)
            + "\nResolve them by hand (for example in the admin) and run "
            "migrate again. Nothing was merged or renamed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securityevent'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            refuse_case_insensitive_duplicates, migrations.RunPython.noop
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.RegexValidator('@', "Usernames can't contain @. That's how sign-in tells them from email addresses.", inverse_match=True)], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_ci', violation_error_message='A user with that username already exists.'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_email_ci', violation_error_message='An account with that email address already exists.'),
        ),
    ]
