# Generated by Django 6.0.6 on 2026-10-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_security_event_cooldown_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
