# Generated by Django 6.0.6 on 2026-10-07 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='kind',
            field=models.CharField(choices=[('sign_up', 'Signed up'), ('sign_in_succeeded', 'Signed in'), ('sign_in_failed', 'Sign-in failed'), ('2fa_code_failed', 'Two-factor code failed'), ('password_changed', 'Password changed'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('email_change_requested', 'Email change requested'), ('email_change_confirmed', 'Email changed'), ('email_verified', 'Email verified'), ('username_changed', 'Username changed'), ('2fa_enabled', 'Two-factor turned on'), ('2fa_disabled', 'Two-factor turned off'), ('2fa_reset', 'Two-factor reset'), ('recovery_codes_regenerated', 'Recovery codes regenerated'), ('recovery_code_used', 'Recovery code used'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('cooldown_started', 'Sign-in paused'), ('cooldown_cleared', 'Sign-in cooldown cleared'), ('other_sessions_ended', 'Signed out of other devices'), ('session_ended', 'Signed out a device')], max_length=32),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='usersession_user_recent')],
            },
        ),
    ]
