# Generated by Django 6.0.6 on 2026-10-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, editable=False, upload_to='avatars'),
        ),
    ]
