# Generated by Django 6.0.6 on 2026-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactordevice',
            name='ask_at_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twofactordevice',
            name='ask_for_security_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='kind',
            field=models.CharField(choices=[('sign_up', 'Signed up'), ('sign_in_succeeded', 'Signed in'), ('sign_in_failed', 'Sign-in failed'), ('2fa_code_failed', 'Two-factor code failed'), ('password_changed', 'Password changed'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('email_change_requested', 'Email change requested'), ('email_change_confirmed', 'Email changed'), ('email_verified', 'Email verified'), ('username_changed', 'Username changed'), ('2fa_enabled', 'Two-factor turned on'), ('2fa_disabled', 'Two-factor turned off'), ('2fa_reset', 'Two-factor reset'), ('2fa_settings_changed', 'Two-factor settings changed'), ('recovery_codes_regenerated', 'Recovery codes regenerated'), ('recovery_code_used', 'Recovery code used'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('cooldown_started', 'Sign-in paused'), ('cooldown_cleared', 'Sign-in cooldown cleared'), ('other_sessions_ended', 'Signed out of other devices'), ('session_ended', 'Signed out a device')], max_length=32),
        ),
    ]
