# Generated by Django 6.0.6 on 2026-09-22 03:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What the customer types. Stored and matched in capitals.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3,20}$', 'Use 3–20 letters and digits, like SUMMER50.')])),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent off'), ('AMOUNT', 'Amount off')], default='PERCENT', max_length=7)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage for “Percent off”, dollars for “Amount off”.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('starts_at', models.DateTimeField(blank=True, help_text='Blank means it is live immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='The first moment the code no longer works. Blank means it runs until retired.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire the code. Past orders are unaffected.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank to discount the whole order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='products.product')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='orders.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcode'),
        ),
    ]
