# Generated by Django 6.0.6 on 2026-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, editable=False, upload_to='products', verbose_name='main image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='main image alt text'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(editable=False, upload_to='products')),
                ('thumbnail', models.ImageField(editable=False, upload_to='products')),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('alt_text', models.CharField(blank=True, editable=False, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
