# Generated by Django 6.0.6 on 2026-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="The product's web address. Left blank, it's made from the name.", max_length=200, unique=True),
        ),
    ]
